source 'http://rubygems.org'

gem 'rails', '3.0.3'
#gem 'rails', :git => 'git://github.com/rails/rails.git'
#gem 'rack', :git => 'git://github.com/rack/rack.git'

gem 'devise'
gem 'mongoid'
#gem 'simple_form', :path => File.expand_path('../../../simple_form/')
gem 'mm_cms', :path => File.expand_path('../../')
